
// Auto-generated by flipper_ir_to_omote.py
#include <string>
#include "applicationInternal/commandHandler.h"
#include "applicationInternal/devices/deviceRegistry.h"
#include "applicationInternal/hardware/hardwarePresenter.h"
#include "device_SonyBravia.h"

uint16_t SONY_TV_POWER;
uint16_t SONY_TV_INPUT;
uint16_t SONY_TV_HOME;
uint16_t SONY_TV_APPS;
uint16_t SONY_TV_TV;
uint16_t SONY_TV_LEFT;
uint16_t SONY_TV_RIGHT;
uint16_t SONY_TV_UP;
uint16_t SONY_TV_DOWN;
uint16_t SONY_TV_ENTER;
uint16_t SONY_TV_BACK;
uint16_t SONY_TV_MUTE;
uint16_t SONY_TV_VOL_UP;
uint16_t SONY_TV_VOL_DN;
uint16_t SONY_TV_CH_NEXT;
uint16_t SONY_TV_CH_PREV;
uint16_t SONY_TV_PLAY;
uint16_t SONY_TV_PAUSE;
uint16_t SONY_TV_STOP;
uint16_t SONY_TV_FWD;
uint16_t SONY_TV_REW;
uint16_t SONY_TV_PREV;
uint16_t SONY_TV_NEXT;
uint16_t SONY_TV_REC;
uint16_t SONY_TV_NETFLIX;
uint16_t SONY_TV_GOOGLE_PLAY;
uint16_t SONY_TV_RED;
uint16_t SONY_TV_GREEN;
uint16_t SONY_TV_YELLOW;
uint16_t SONY_TV_BLUE;
uint16_t SONY_TV_ACTION_MENU;
uint16_t SONY_TV_GUIDE;
uint16_t SONY_TV_HELP;
uint16_t SONY_TV_TITLE_LIST;
uint16_t SONY_TV_AUDIO;
uint16_t SONY_TV_SCREEN;
uint16_t SONY_TV_SWAP;
uint16_t SONY_TV_DIG_ANALO;
uint16_t SONY_TV_TV_RADIO;
uint16_t SONY_TV_EXIT;
uint16_t SONY_TV_EXT_BOX_MENU;
uint16_t SONY_TV_1;
uint16_t SONY_TV_2;
uint16_t SONY_TV_3;
uint16_t SONY_TV_4;
uint16_t SONY_TV_5;
uint16_t SONY_TV_6;
uint16_t SONY_TV_7;
uint16_t SONY_TV_8;
uint16_t SONY_TV_9;
uint16_t SONY_TV_0;
uint16_t SONY_TV_I_PLUS;
uint16_t SONY_TV_TXT;

void register_device_SonyBravia() {
    Device* dev = deviceRegistry::registerDevice("SONY_TV");
    register_command(&SONY_TV_APPS, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x23:15:2"})); // Apps
    register_command(&SONY_TV_TV, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Tv
    register_command(&SONY_TV_LEFT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Left
    register_command(&SONY_TV_RIGHT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Right
    register_command(&SONY_TV_UP, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Up
    register_command(&SONY_TV_DOWN, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Down
    register_command(&SONY_TV_ENTER, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Enter
    register_command(&SONY_TV_BACK, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Back
    register_command(&SONY_TV_MUTE, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Mute
    register_command(&SONY_TV_VOL_UP, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Vol_up
    register_command(&SONY_TV_VOL_DN, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Vol_dn
    register_command(&SONY_TV_CH_NEXT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Ch_next
    register_command(&SONY_TV_CH_PREV, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Ch_prev
    register_command(&SONY_TV_PLAY, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Play
    register_command(&SONY_TV_PAUSE, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Pause
    register_command(&SONY_TV_STOP, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Stop
    register_command(&SONY_TV_FWD, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Fwd
    register_command(&SONY_TV_REW, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Rew
    register_command(&SONY_TV_PREV, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Prev
    register_command(&SONY_TV_NEXT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Next
    register_command(&SONY_TV_REC, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Rec
    register_command(&SONY_TV_NETFLIX, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xB:15:2"})); // Netflix
    register_command(&SONY_TV_GOOGLE_PLAY, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x23:15:2"})); // Google_play
    register_command(&SONY_TV_RED, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Red
    register_command(&SONY_TV_GREEN, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Green
    register_command(&SONY_TV_YELLOW, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Yellow
    register_command(&SONY_TV_BLUE, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Blue
    register_command(&SONY_TV_ACTION_MENU, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x23:15:2"})); // Action_menu
    register_command(&SONY_TV_GUIDE, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x25:15:2"})); // Guide
    register_command(&SONY_TV_HELP, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x23:15:2"})); // Help
    register_command(&SONY_TV_TITLE_LIST, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xB:15:2"})); // Title_list
    register_command(&SONY_TV_AUDIO, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Audio
    register_command(&SONY_TV_SCREEN, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xE9:15:2"})); // Screen___
    register_command(&SONY_TV_SWAP, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Swap
    register_command(&SONY_TV_DIG_ANALO, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x77:15:2"})); // Dig_analo
    register_command(&SONY_TV_TV_RADIO, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0xB:15:2"})); // Tv_radio
    register_command(&SONY_TV_EXIT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Exit
    register_command(&SONY_TV_EXT_BOX_MENU, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x23:15:2"})); // Ext_box_menu
    register_command(&SONY_TV_1, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 1
    register_command(&SONY_TV_2, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 2
    register_command(&SONY_TV_3, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 3
    register_command(&SONY_TV_4, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 4
    register_command(&SONY_TV_5, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 5
    register_command(&SONY_TV_6, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 6
    register_command(&SONY_TV_7, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 7
    register_command(&SONY_TV_8, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 8
    register_command(&SONY_TV_9, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 9
    register_command(&SONY_TV_0, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // 0
    register_command(&SONY_TV_I_PLUS, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // I_plus
    register_command(&SONY_TV_TXT, makeCommandData(IR, {std::to_string(IR_PROTOCOL_SONY), "0x1:12:2"})); // Txt
}
