
#pragma once
// Auto-generated by flipper_ir_to_omote.py
void register_device_SonyBravia(void);

extern uint16_t SONY_TV_POWER;
extern uint16_t SONY_TV_INPUT;
extern uint16_t SONY_TV_HOME;

extern uint16_t SONY_TV_APPS;
extern uint16_t SONY_TV_TV;
extern uint16_t SONY_TV_LEFT;
extern uint16_t SONY_TV_RIGHT;
extern uint16_t SONY_TV_UP;
extern uint16_t SONY_TV_DOWN;
extern uint16_t SONY_TV_ENTER;
extern uint16_t SONY_TV_BACK;
extern uint16_t SONY_TV_MUTE;
extern uint16_t SONY_TV_VOL_UP;
extern uint16_t SONY_TV_VOL_DN;
extern uint16_t SONY_TV_CH_NEXT;
extern uint16_t SONY_TV_CH_PREV;
extern uint16_t SONY_TV_PLAY;
extern uint16_t SONY_TV_PAUSE;
extern uint16_t SONY_TV_STOP;
extern uint16_t SONY_TV_FWD;
extern uint16_t SONY_TV_REW;
extern uint16_t SONY_TV_PREV;
extern uint16_t SONY_TV_NEXT;
extern uint16_t SONY_TV_REC;
extern uint16_t SONY_TV_NETFLIX;
extern uint16_t SONY_TV_GOOGLE_PLAY;
extern uint16_t SONY_TV_RED;
extern uint16_t SONY_TV_GREEN;
extern uint16_t SONY_TV_YELLOW;
extern uint16_t SONY_TV_BLUE;
extern uint16_t SONY_TV_ACTION_MENU;
extern uint16_t SONY_TV_GUIDE;
extern uint16_t SONY_TV_HELP;
extern uint16_t SONY_TV_TITLE_LIST;
extern uint16_t SONY_TV_AUDIO;
extern uint16_t SONY_TV_SCREEN;
extern uint16_t SONY_TV_SWAP;
extern uint16_t SONY_TV_DIG_ANALO;
extern uint16_t SONY_TV_TV_RADIO;
extern uint16_t SONY_TV_EXIT;
extern uint16_t SONY_TV_EXT_BOX_MENU;
extern uint16_t SONY_TV_BUTTON_1;
extern uint16_t SONY_TV_BUTTON_2;
extern uint16_t SONY_TV_BUTTON_3;
extern uint16_t SONY_TV_BUTTON_4;
extern uint16_t SONY_TV_BUTTON_5;
extern uint16_t SONY_TV_BUTTON_6;
extern uint16_t SONY_TV_BUTTON_7;
extern uint16_t SONY_TV_BUTTON_8;
extern uint16_t SONY_TV_BUTTON_9;
extern uint16_t SONY_TV_BUTTON_0;
extern uint16_t SONY_TV_I_PLUS;
extern uint16_t SONY_TV_TXT;
